### ISSUE TITLE
Custom morus topics missing in logger

### ISSUE THREAD

**Issue by aivano** [larics/px4-firmware#9]
Missing topics of interest from msg/morus are:
attitude_controller_status
attitude_controller_reference
mcu_controllers_reference
ctrl_sm_controllers_reference
mcu_controllers_mode
commander_controllers_mode
position_controller_status
commander_position_controller_setpoint
gas_motor_setpoint_array
commander_gas_motor_ignition_reference

Please add these topics to sdlog2 module.

**Comment by lmark1** [comment]
Finished adding topics.

Four letter topic abbreviations, found in logs: 
CREF - Controller reference
ACSR - Attitude controller status - roll
ASRR - Attitude controller status - roll - rate
ACSP - Attitude controller status - pitch
ASPR - Attitude controller status - pitch - rate
ACSY - Attitude controller status - yaw
ASYR - Attitude controller status - yaw - rate
ASRV - Attitude controller status - roll - rate - vpc
ASPV - Attitude controller status - pitch - rate - vpc
ATCR - Attitude controller reference
MCRE - MCU - controller reference
SMRE - Control-SM controller reference
MCMD - MCU - controllers mode
CCMD - Commander - controllers mode
PCSX - Position controller status - x
PCVX - Position controller status - vx
PCSY - Position controller status - y
PCVY - Position controller status - vy
PCSZ - Position controller status - z
PCVZ - Position controller status - vz
PCSP - Position controller setpoint
GMSP - Gas motor setpoint array
MIRE - Gas motor ignition reference

Topic suffixes should be more intuitive.
